config {
  type: "table",
  database: "amrl-data-prd",
  schema: "WKS_COTIZACIONES_ML",
  name: "03_Obt_Cotizaciones_split"
}

WITH base_data AS (

  SELECT 
    *,
    RAND() AS random_val
  FROM ${ref("02_Obt_Cotizaciones")}

),

stratified AS (

  SELECT 
    *,
    NTILE(5) OVER(
      PARTITION BY COMPRO 
      ORDER BY random_val
    ) AS fold
  FROM base_data

)

SELECT 
  * EXCEPT(random_val, fold),

  IF(fold = 1, TRUE, FALSE) AS USO_ML

FROM stratified