config {
  type: "operations",
  hasOutput: true
}
---------------------------------------------------
-- MODELO BOOSTED TREE
---------------------------------------------------
CREATE OR REPLACE MODEL `${dataform.projectConfig.defaultDatabase}.WKS_COTIZACIONES_ML.10_boosted_tree_model_cotizaciones`
OPTIONS(
  MODEL_TYPE = 'BOOSTED_TREE_CLASSIFIER',
  INPUT_LABEL_COLS = ['COMPRO'],
  ---------------------------------------------------
  -- SPLIT
  ---------------------------------------------------
  DATA_SPLIT_METHOD = 'CUSTOM',
  DATA_SPLIT_COL = 'IS_TEST',
  ---------------------------------------------------
  -- BALANCEO
  ---------------------------------------------------
  AUTO_CLASS_WEIGHTS = TRUE,
  ---------------------------------------------------
  -- EXPLAINABILITY
  ---------------------------------------------------
  ENABLE_GLOBAL_EXPLAIN = TRUE,
  ---------------------------------------------------
  -- HIPERPARÁMETROS
  ---------------------------------------------------
  MAX_ITERATIONS = 300,
  MAX_TREE_DEPTH = 6,
  SUBSAMPLE = 0.8,
  LEARN_RATE = 0.05,
  COLSAMPLE_BYTREE = 0.8,
  MIN_TREE_CHILD_WEIGHT = 5,
  MIN_SPLIT_LOSS = 1,
  L1_REG = 0.1,
  L2_REG = 1.0,
  EARLY_STOP = TRUE
) AS

SELECT
    * EXCEPT(
        ID_COTIZACION,
        HASH_CONTROL,
        IDENTIFICACION_COMPRADOR1,
        COMPRADOR1,
        BK_NUMERO_OP,
        EDAD,
        NUM_COMPRAS_ANTERIORES,
        CIUDAD_PROYECTO_DE_INTERES,
        FECHA_ULTIMA_COTIZACION

    )

FROM ${ref("03_Obt_Cotizaciones_split")}