config {
  type: "incremental",
  schema: "WKS_COTIZACIONES_ML",
  tags: ["MONITORING"],
  name: "05_prd_boosted_tree_model",
  
}

--uniqueKey: ["ID_COTIZACION"]

SELECT
   --TIMESTAMP('2026-06-01 07:26:05') AS FECHA_SCORING , --CARGAS INCREMENTALES MANUALES
   CURRENT_TIMESTAMP() AS FECHA_SCORING,
    P.*

FROM ML.PREDICT(

    MODEL `amrl-data-prd.WKS_COTIZACIONES_ML.01_boosted_tree_model_cotizaciones`,
    (
        SELECT
            * 
        FROM ${ref("04_Obt_Cotizaciones_incremental")}
        --WHERE DATE(FECHA_CARGUE_ML)= CURRENT_DATE("America/Bogota")
       --WHERE DATE(FECHA_CARGUE_ML) = '2026-06-01'--CARGAS INCREMENTALES MANUALES
    )

) AS P