config {
    type: "incremental",
    tags: ["MONITORING"],
    name: "05_prd_monitoring_metricas_modelo",
    description: "Tabla histórica para monitorear las métricas del modelo en el tiempo."
}

SELECT 

    CURRENT_TIMESTAMP() AS FECHA_SCORING,
    0.5 AS THRESHOLD_PREDICCION,
    *

FROM ML.EVALUATE(
    MODEL `amrl-data-prd.WKS_COTIZACIONES_ML.01_boosted_tree_model_cotizaciones`,
    (   SELECT* 
        FROM ${ref("04_Obt_Cotizaciones_incremental")}
    ),
    STRUCT(
        0.35 AS threshold
    )

)